export const SHOP_GET_CUSTOMER_DETAILS_REQUEST = 'SHOP_GET_CUSTOMER_DETAILS_REQUEST'
export const SHOP_GET_CUSTOMER_DETAILS_SUCCESS = 'SHOP_GET_CUSTOMER_DETAILS_SUCCESS'
export const SHOP_GET_CUSTOMER_DETAILS_FAILURE = 'SHOP_GET_CUSTOMER_DETAILS_FAILURE'
export const SHOP_GET_CUSTOMER_DETAILS_API_ERROR_MESSAGES = {
  'ERROR': 'Failed to get user contacts.',
  'NOT_AUTHORISED': 'Please login.'
}

export const SHOP_SAVE_CUSTOMER_DETAILS_REQUEST = 'SHOP_SAVE_CUSTOMER_DETAILS_REQUEST'
export const SHOP_SAVE_CUSTOMER_DETAILS_SUCCESS = 'SHOP_SAVE_CUSTOMER_DETAILS_SUCCESS'
export const SHOP_SAVE_CUSTOMER_DETAILS_FAILURE = 'SHOP_SAVE_CUSTOMER_DETAILS_FAILURE'
export const SHOP_SAVE_CUSTOMER_DETAILS_API_ERROR_MESSAGES = {
  'ERROR': 'Failed to save user contacts.',
  'NOT_AUTHORISED': 'Please login.'
}

export const SHOP_GET_COUNTRY_LIST_REQUEST = 'SHOP_GET_COUNTRY_LIST_REQUEST'
export const SHOP_GET_COUNTRY_LIST_SUCCESS = 'SHOP_GET_COUNTRY_LIST_SUCCESS'
export const SHOP_GET_COUNTRY_LIST_FAILURE= 'SHOP_GET_COUNTRY_LIST_FAILURE'
export const SHOP_GET_COUNTRY_LIST_API_ERROR_MESSAGES = {
  'ERROR': 'Failed to get country list.'
}

export const SHOP_GET_PRODUCTS_REQUEST = 'SHOP_GET_PRODUCTS_REQUEST'
export const SHOP_GET_PRODUCTS_SUCCESS = 'SHOP_GET_PRODUCTS_SUCCESS'
export const SHOP_GET_PRODUCTS_FAILURE = 'SHOP_GET_PRODUCTS_FAILURE'
export const SHOP_GET_PRODUCTS_API_ERROR_MESSAGES = {
  'ERROR': 'Failed to get shop products.',
  'NO_PRODUCTS_FOUND': 'There are no products available.'
}

export const SHOP_RESET_API_ERRORS = 'SHOP_RESET_API_ERRORS'

export const SHOP_UPDATE_BASKET_REQUEST = 'SHOP_UPDATE_BASKET_REQUEST'
