export const PROTEUS_GET_MODULES_REQUEST = 'PROTEUS_GET_MODULES_REQUEST'
export const PROTEUS_GET_MODULES_SUCCESS = 'PROTEUS_GET_MODULES_SUCCESS'
export const PROTEUS_GET_MODULES_FAILURE = 'PROTEUS_GET_MODULES_FAILURE'

export const PROTEUS_MODULES_API_ERROR_MESSAGES = {
  'OOPS': 'Get modules failed.'
}