export const USER_PROFILE_GET_DETAILS_REQUEST = 'USER_PROFILE_GET_DETAILS_REQUEST'
export const USER_PROFILE_GET_DETAILS_SUCCESS = 'USER_PROFILE_GET_DETAILS_SUCCESS'
export const USER_PROFILE_GET_DETAILS_FAILURE = 'USER_PROFILE_GET_DETAILS_FAILURE'
export const USER_PROFILE_GET_DETAILS_API_ERROR_MESSAGES = {
  'ERROR': 'Failed to get profile details.',
  'PROFILE_NOT_FOUND': 'Profile not found.',
  'USER_NOT_FOUND': 'User not found.'
}